const API='http://localhost:8080/api/v1';
const IMGS={WEDDING:'https://images.unsplash.com/photo-1519741497674-611481863552?q=80&w=800&auto=format&fit=crop',BIRTHDAY:'https://images.unsplash.com/photo-1530103043960-ef38714abb15?q=80&w=800&auto=format&fit=crop',CORPORATE:'https://images.unsplash.com/photo-1511578314322-379afb476865?q=80&w=800&auto=format&fit=crop',CONCERT:'https://images.unsplash.com/photo-1459749411177-042180ce6742?q=80&w=800&auto=format&fit=crop',GRADUATION:'https://images.unsplash.com/photo-1523050854058-8df90110c9f1?q=80&w=800&auto=format&fit=crop',GALA:'https://images.unsplash.com/photo-1478147427282-58a87a120781?q=80&w=800&auto=format&fit=crop',CONFERENCE:'https://images.unsplash.com/photo-1540575467063-178a50c2df87?q=80&w=800&auto=format&fit=crop',DEFAULT:'https://images.unsplash.com/photo-1511795409834-ef04bbd61622?q=80&w=800&auto=format&fit=crop'};
const VIMGS={PHOTOGRAPHY:'https://images.unsplash.com/photo-1502920917128-1aa500764cbd?q=80&w=600&auto=format&fit=crop',CATERING:'https://images.unsplash.com/photo-1567521464027-f127ff144326?q=80&w=600&auto=format&fit=crop',DECORATION:'https://images.unsplash.com/photo-1478147427282-58a87a120781?q=80&w=600&auto=format&fit=crop',MUSIC:'https://images.unsplash.com/photo-1493225457124-a3eb161ffa5f?q=80&w=600&auto=format&fit=crop',VENUE:'https://images.unsplash.com/photo-1519167758481-83f550bb49b3?q=80&w=600&auto=format&fit=crop',TRANSPORT:'https://images.unsplash.com/photo-1544620347-c4fd4a3d5957?q=80&w=600&auto=format&fit=crop',DEFAULT:'https://images.unsplash.com/photo-1511795409834-ef04bbd61622?q=80&w=600&auto=format&fit=crop'};
const Auth={token:()=>localStorage.getItem('token'),role:()=>(localStorage.getItem('userRole')||'').toUpperCase(),email:()=>localStorage.getItem('userEmail'),userId:()=>localStorage.getItem('userId'),name:()=>localStorage.getItem('userName')||(Auth.email()||'').split('@')[0].toUpperCase(),headers:()=>({'Content-Type':'application/json','Authorization':'Bearer '+Auth.token()}),logout:()=>{localStorage.clear();location.href='login.html';},guard:(role)=>{if(!Auth.token()){location.href='login.html';return false;}if(role&&Auth.role()!==role.toUpperCase()){location.href='login.html';return false;}return true;}};
async function api(method,path,body=null){const o={method,headers:Auth.headers()};if(body)o.body=JSON.stringify(body);const r=await fetch(API+path,o);if(!r.ok){const e=await r.json().catch(()=>({message:'Server error'}));throw new Error(e.message||`HTTP ${r.status}`);}return r.json();}
function toast(msg,type='info'){let c=document.getElementById('toast-cnt');if(!c){c=document.createElement('div');c.id='toast-cnt';document.body.appendChild(c);}const ic={success:'fa-check-circle',error:'fa-exclamation-circle',info:'fa-info-circle'};const cl={success:'#22C98B',error:'#F06060',info:'#C9A84C'};const t=document.createElement('div');t.className=`toast ${type}`;t.innerHTML=`<i class="fas ${ic[type]}" style="color:${cl[type]}"></i><span>${msg}</span>`;c.appendChild(t);setTimeout(()=>{t.style.opacity='0';t.style.transform='translateX(100px)';t.style.transition='all .3s';setTimeout(()=>t.remove(),300);},3200);}
function openModal(id){document.getElementById(id)?.classList.add('open');}
function closeModal(id){document.getElementById(id)?.classList.remove('open');}
document.addEventListener('click',e=>{if(e.target.classList.contains('modal-ov'))e.target.classList.remove('open');});
function badge(s){const m={PENDING:'b-pending',APPROVED:'b-approved',CONFIRMED:'b-confirmed',PAID:'b-paid',UNPAID:'b-unpaid',CANCELLED:'b-cancelled',REQUESTED:'b-requested',REJECTED:'b-cancelled',ADMIN:'b-admin',CLIENT:'b-client',STAFF:'b-staff'};return`<span class="badge ${m[(s||'').toUpperCase()]||'b-pending'}">${s||'—'}</span>`;}
function eImg(t){return IMGS[(t||'').toUpperCase()]||IMGS.DEFAULT;}
function vImg(t){return VIMGS[(t||'').toUpperCase()]||VIMGS.DEFAULT;}
function fDate(d){if(!d)return'—';return new Date(d).toLocaleDateString('en-US',{year:'numeric',month:'short',day:'numeric'});}
function fLKR(n){return'LKR '+Number(n||0).toLocaleString('en-US',{minimumFractionDigits:2});}
function fillUser(){const n=Auth.name();document.querySelectorAll('[data-uname]').forEach(e=>e.textContent=n);document.querySelectorAll('[data-urole]').forEach(e=>e.textContent=Auth.role());document.querySelectorAll('[data-uav]').forEach(e=>e.textContent=n.charAt(0));}
function loadRow(cols=5){return`<tr><td colspan="${cols}"><div class="load-st"><div class="sp"></div><span>Loading...</span></div></td></tr>`;}
function emptyRow(cols,msg='No records found'){return`<tr><td colspan="${cols}"><div class="empty-st"><i class="fas fa-inbox"></i><h4>${msg}</h4><p>Records will appear here once available</p></div></td></tr>`;}
